### ISSUE TITLE
Enable Cuda Hw acceleration

### ISSUE THREAD

**Issue by mikysal78** [WinFF/winff#243]
Debian Buster 64bit
If run ffmpeg from cmd line is ok, if change present in winff not work.... because?

**Comment by paulgevers** [comment]
No idea. Could you please copy/paste any output in the command window? Also, is this the winff package installed via Debian packages or did you compile yourself?

**Comment by paulgevers** [comment]
If I remember correctly (it has been a while since I used WinFF myself) WinFF doesn't have the feature to add options the correct stream for this to work. Apparently the option you want here, needs to go in a different location on the command line that WinFF puts it. I don't think there's a way around this.

If I remember correctly, there is a wishlist bug open for this support.

**Comment by paulgevers** [comment]
Like #238 and #241
